Handling the case where there are no changes when removing a test instance.  This doens't happen much, but it's super annoying to get spam when you're working on a bunch of things.

diff --git a/.github/workflows/remove-test.yml b/.github/workflows/remove-test.yml
--- a/.github/workflows/remove-test.yml
+++ b/.github/workflows/remove-test.yml
@@ -62,9 +62,5 @@ jobs:
         working-directory: admin-interface-test
         run: |
           git add .
-          git commit -m "Remove deployment ${PR_NUMBER} due to PR closure" || true
-
-      - name: push updates
-        working-directory: admin-interface-test
-        run: |
-          git push origin gh-pages
+          # Commit and push, or just say true since the commit fails if nothing has changed
+          (git commit -m "Remove deployment ${PR_NUMBER} due to PR closure" && git push origin gh-pages --force) || true
